spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  application:
    name: personnel-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/personnel-db
    username: team3-db-user
    password: team3DbPassword
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog.xml